### ISSUE TITLE
Cannot install KDE-mac/kde/libkexiv2

### ISSUE THREAD

**Issue by uiiji** [KDE-mac/homebrew-kde#277] opened 2019-01-12 18:29 UTC
I was trying to install okular on my mac, but cannot install libkexiv2.

==> Installing okular from kde-mac/kde
==> Installing dependencies for kde-mac/kde/okular: KDE-mac/kde/libkexiv2 and poppler
==> Installing kde-mac/kde/okular dependency: KDE-mac/kde/libkexiv2
==> Downloading https://download.kde.org/stable/applications/18.12.0/src/libkexiv2-18.12.0.tar.xz
Already downloaded: /Users/tert/Library/Caches/Homebrew/downloads/dbb46ae71bf279dcb60000b0e1afeafc3c95a2b741f966bea3b89044e4e73102--libkexiv2-18.12.0.tar.xz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cell
Last 15 lines from /Users/tert/Library/Logs/Homebrew/libkexiv2/01.cmake:
-- Performing Test HAVE_DATE_TIME
-- Performing Test HAVE_DATE_TIME - Success
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
CMake Error at /usr/local/Cellar/cmake/3.13.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Exiv2: Found unsuitable version "..", but required is at
  least "0.24" (found /usr/local/lib/libexiv2.dylib)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.13.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:376 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindExiv2.cmake:76 (find_package_handle_standard_args)
  CMakeLists.txt:87 (find_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/libkexiv2-20190113-73124-1vhiiou/libkexiv2-18.12.0/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/libkexiv2-20190113-73124-1vhiiou/libkexiv2-18.12.0/build/CMakeFiles/CMakeError.log".

I have already had exiv2 installed via homebrew.
Please help! Thx!

**Comment by yurikoles** [comment] 2019-01-12 18:35
Seems to be regression in upstream. I will issue a ticket.

**Comment by yurikoles** [comment] 2019-01-12 19:08
https://bugs.kde.org/show_bug.cgi?id=403152

**Comment by yurikoles** [comment] 2019-01-12 19:09
https://bugs.kde.org/show_bug.cgi?id=403152

**Comment by wschlich** [comment] 2019-01-14 09:16
See https://trac.macports.org/ticket/57803 for a possible fix/patch.

**Comment by sudoyang** [comment] 2019-01-24 20:54
I meet same problem on most recent macOS 10.14.3.

**Comment by neer201** [comment] 2019-02-18 10:39
> See https://trac.macports.org/ticket/57803 for a possible fix/patch.

Guys, could you please describe how it can be fixed? On macOS 10.14.3

**Comment by wschlich** [comment] 2019-02-18 10:46
> > See https://trac.macports.org/ticket/57803 for a possible fix/patch.
> 
> Guys, could you please describe how it can be fixed? On macOS 10.14.3

Apply https://trac.macports.org/attachment/ticket/57803/patch-FindExiv2.diff

**Comment by neer201** [comment] 2019-02-18 15:23
I am stuck with that
'''
$ sudo patch -p0 < ~/Downloads/patch-FindExiv2.diff
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- kdelibs-4.14.3-orig/cmake/modules/FindExiv2.cmake 2014-11-07
07:33:50.000000000 +0900
|+++ kdelibs-4.14.3/cmake/modules/FindExiv2.cmake 2018-12-24
15:47:52.000000000 +0900
--------------------------
File to patch:
Skip this patch? [y]
Skipping patch.
1 out of 1 hunk ignored
'''


пн, 18 февр. 2019 г. в 13:46, Wolfram Schlich <notifications@github.com>:

**Comment by neer201** [comment] 2019-02-28 15:38
Guys, could you please help?)

**Comment by sl1pkn07** [comment] 2019-03-17 13:16
Hi. i've tested the pach and not work

applies ok, but fail build

~~~
[5/16] Building CXX object src/CMakeFiles/KF5KExiv2.dir/kexiv2data.cpp.o
../src/kexiv2data.cpp:38:9: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
    : d(0)
        ^
        nullptr
1 warning generated.
[6/16] Building CXX object src/CMakeFiles/KF5KExiv2.dir/kexiv2.cpp.o
FAILED: src/CMakeFiles/KF5KExiv2.dir/kexiv2.cpp.o 
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DKF5KExiv2_EXPORTS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MAC_USE_COCOA -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_SIGNALS_SLOTS_KEYWORDS -DQT_NO_URL_CAST_FROM_STRING -DQT_USE_QSTRINGBUILDER -D_DARWIN_C_SOURCE -D_LARGEFILE64_SOURCE -Isrc -I../src -Isrc/KF5KExiv2_autogen/include -Isrc/.. -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -std=c++0x -fno-operator-names -Wno-gnu-zero-variadic-macro-arguments -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -fdiagnostics-color=always -pedantic -Wzero-as-null-pointer-constant -fexceptions -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -std=gnu++11 -MD -MT src/CMakeFiles/KF5KExiv2.dir/kexiv2.cpp.o -MF src/CMakeFiles/KF5KExiv2.dir/kexiv2.cpp.o.d -o src/CMakeFiles/KF5KExiv2.dir/kexiv2.cpp.o -c ../src/kexiv2.cpp
../src/kexiv2.cpp:156:32: error: no member named 'version' in namespace 'Exiv2'; did you mean 'qVersion'?
    return QString::fromLatin1(Exiv2::version());
                               ^~~~~~~~~~~~~~
                               qVersion
/usr/local/opt/qt/include/QtCore/qglobal.h:406:49: note: 'qVersion' declared here
Q_CORE_EXPORT Q_DECL_CONST_FUNCTION const char *qVersion(void) Q_DECL_NOTHROW;
                                                ^
1 error generated.
[7/16] Building CXX object src/CMakeFiles/KF5KExiv2.dir/kexiv2previews.cpp.o
../src/kexiv2previews.cpp:44:19: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
        manager = 0;
                  ^
                  nullptr
1 warning generated.
[8/16] Building CXX object src/CMakeFiles/KF5KExiv2.dir/kexiv2comments.cpp.o
[9/16] Building CXX object src/CMakeFiles/KF5KExiv2.dir/kexiv2exif.cpp.o
FAILED: src/CMakeFiles/KF5KExiv2.dir/kexiv2exif.cpp.o 
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DKF5KExiv2_EXPORTS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MAC_USE_COCOA -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_SIGNALS_SLOTS_KEYWORDS -DQT_NO_URL_CAST_FROM_STRING -DQT_USE_QSTRINGBUILDER -D_DARWIN_C_SOURCE -D_LARGEFILE64_SOURCE -Isrc -I../src -Isrc/KF5KExiv2_autogen/include -Isrc/.. -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -std=c++0x -fno-operator-names -Wno-gnu-zero-variadic-macro-arguments -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -fdiagnostics-color=always -pedantic -Wzero-as-null-pointer-constant -fexceptions -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -std=gnu++11 -MD -MT src/CMakeFiles/KF5KExiv2.dir/kexiv2exif.cpp.o -MF src/CMakeFiles/KF5KExiv2.dir/kexiv2exif.cpp.o.d -o src/CMakeFiles/KF5KExiv2.dir/kexiv2exif.cpp.o -c ../src/kexiv2exif.cpp
../src/kexiv2exif.cpp:990:19: error: no matching constructor for initialization of 'Exiv2::Error' (aka 'BasicError<char>')
            throw Exiv2::Error(1, "Exif.Image.NewSubfileType missing or not set as main image");
                  ^            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/exiv2/error.hpp:272:9: note: candidate constructor not viable: no known conversion from 'int' to 'Exiv2::ErrorCode' for 1st argument
        BasicError(ErrorCode code, const A& arg1);
        ^
/usr/local/include/exiv2/error.hpp:276:9: note: candidate constructor template not viable: requires 3 arguments, but 2 were provided
        BasicError(ErrorCode code, const A& arg1, const B& arg2);
        ^
/usr/local/include/exiv2/error.hpp:280:9: note: candidate constructor template not viable: requires 4 arguments, but 2 were provided
        BasicError(ErrorCode code, const A& arg1, const B& arg2, const C& arg3);
        ^
/usr/local/include/exiv2/error.hpp:268:18: note: candidate constructor not viable: requires single argument 'code', but 2 arguments were provided
        explicit BasicError(ErrorCode code);
                 ^
/usr/local/include/exiv2/error.hpp:263:11: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
    class BasicError : public AnyError {
          ^
../src/kexiv2exif.cpp:1065:32: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
        while (gi->tagList_ != 0)
                               ^
                               nullptr
../src/kexiv2exif.cpp:1117:32: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
        while (gi->tagList_ != 0)
                               ^
                               nullptr
2 warnings and 1 error generated.
[10/16] Building CXX object src/CMakeFiles/KF5KExiv2.dir/kexiv2_p.cpp.o
FAILED: src/CMakeFiles/KF5KExiv2.dir/kexiv2_p.cpp.o 
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++  -DKF5KExiv2_EXPORTS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_MAC_USE_COCOA -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_SIGNALS_SLOTS_KEYWORDS -DQT_NO_URL_CAST_FROM_STRING -DQT_USE_QSTRINGBUILDER -D_DARWIN_C_SOURCE -D_LARGEFILE64_SOURCE -Isrc -I../src -Isrc/KF5KExiv2_autogen/include -Isrc/.. -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -std=c++0x -fno-operator-names -Wno-gnu-zero-variadic-macro-arguments -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -fdiagnostics-color=always -pedantic -Wzero-as-null-pointer-constant -fexceptions -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -std=gnu++11 -MD -MT src/CMakeFiles/KF5KExiv2.dir/kexiv2_p.cpp.o -MF src/CMakeFiles/KF5KExiv2.dir/kexiv2_p.cpp.o.d -o src/CMakeFiles/KF5KExiv2.dir/kexiv2_p.cpp.o -c ../src/kexiv2_p.cpp
../src/kexiv2_p.cpp:134:16: error: no member named 'testVersion' in namespace 'Exiv2'
    if (Exiv2::testVersion(0,23,0))
        ~~~~~~~^
../src/kexiv2_p.cpp:152:17: error: no member named 'testVersion' in namespace 'Exiv2'
    if (!Exiv2::testVersion(0,23,0))
         ~~~~~~~^
../src/kexiv2_p.cpp:471:5: warning: 'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
    register unsigned char c;
    ^~~~~~~~~
1 warning and 2 errors generated.
[11/16] Building CXX object src/CMakeFiles/KF5KExiv2.dir/kexiv2gps.cpp.o
[12/16] Building CXX object src/CMakeFiles/KF5KExiv2.dir/kexiv2image.cpp.o
[13/16] Building CXX object src/CMakeFiles/KF5KExiv2.dir/kexiv2iptc.cpp.o
../src/kexiv2iptc.cpp:96:51: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
                c2 = Exiv2::Photoshop::setIptcIrb(0, 0, iptc);
                                                  ^
                                                  nullptr
1 warning generated.
[14/16] Building CXX object src/CMakeFiles/KF5KExiv2.dir/kexiv2xmp.cpp.o
ninja: build stopped: subcommand failed.

**Comment by sl1pkn07** [comment] 2019-03-17 13:30
fixed by 21c03a37830878625789c66ea62c435632c99252

closing

greetings

**Closed by sl1pkn07** 2019-03-17 13:30 UTC
Labels: upstream

**Comment by yurikoles** [comment] 2019-03-17 13:59
@sl1pkn07, thanks!

**Comment by neer201** [comment] 2019-03-21 10:32
Now installation of  KDE-mac/kde/libkexiv2 failed with:
`Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: e47869b9ab5640d0ead20d645b0bdf07cec3f4a5b52749b5de303c6dd27faf8c
Actual: 8fc831c6918b7a274de1fa7737dd678d127299552f3e564a110d58898ae8af17`

**Comment by sl1pkn07** [comment] 2019-03-21 16:40
try now

**Comment by sudoyang** [comment] 2019-03-21 16:52
@neer201 
I guess it is due to that you modified libkexiv2 install file (libkexiv2-18.12.1.tar.xz) manually so the checksummatch complains. Homebrew detects the modified file and won't download the original one to overwrite it.
You need to remove the modified file and let homebrew to download the new one
In my case, it is like
`rm /Users/godel/Library/Caches/Homebrew/downloads/219f5973861e1456f2eec7efc23c239e6c576f4a625ef51f13a6d680189f0de7--libkexiv2-18.12.1.tar.xz`
and then
`brew update && brew upgrade && brew cleanup`

**Comment by sl1pkn07** [comment] 2019-03-21 17:19
the main problem is, is not the same download the patch from gitgub with:

https://github.com/KDE/libkexiv2/commit/d1be9298c7f2b9c717cda154d41732f230ea13a6.patch?full_index=1

than with

https://github.com/KDE/libkexiv2/commit/d1be9298c7f2b9c717cda154d41732f230ea13a6.patch

when i added the patch i used the last one link, with the old SHA256. the new link generate the new SHA256 which i forgot edit in the formula

greetings

**Comment by neer201** [comment] 2019-03-21 17:25
Thanks! Step forward)

Now I get

**Comment by sl1pkn07** [comment] 2019-03-21 17:30
what version of exiv2 you use?. you made  `brew cleanup` for purge the older version of the formulas?

**Comment by neer201** [comment] 2019-03-21 17:45
Ooops! You are right.

Hooray! Now it works! Thank you very much! =)
