### ISSUE TITLE
kf5-konsole

### ISSUE THREAD

**Issue by imyelmo** [KDE-mac/homebrew-kde#117] opened 2017-06-09 10:53 UTC
I'm trying to get working konsole. 

It seems necessary to remove first patch on the formula, it is not longer necessary:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a3d9a1c..793e586 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -41,6 +41,6 @@ include_directories(${CMAKE_SOURCE_DIR} ${CMAKE_BINARY_DIR} ${KDE4_INCLUDES})
 add_subdirectory( src )
 add_subdirectory( data )
 add_subdirectory( desktop )
-add_subdirectory( doc/manual )
+#add_subdirectory( doc/manual )
 
 feature_summary(WHAT ALL INCLUDE_QUIET_PACKAGES FATAL_ON_MISSING_REQUIRED_PACKAGES)
```

However, other error remains:

```
ld: library not found for -lKF5::KDELibs4Support
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/libkonsoleprivate.17.04.1.dylib] Error 1
make[1]: *** [src/CMakeFiles/konsoleprivate.dir/all] Error 2
make: *** [all] Error 2
```

but kf5-kdelibs4support package is installed and directory "/usr/local/include/KF5/KDELibs4Support" exists and this workaround doesn't fix the problem:

```cd /usr/local/include
ln -s ../opt/kf5-kdelibs4support/include/KF5/KDELibs4Support/ .
```

Where is CMake looking for the KDELibs4Support headers?

**Comment by sl1pkn07** [comment] 2017-10-23 21:25
seems the second patch not need anymore

tested without both hunks and build OK

can't run due my several problems with dbus (refuse to load)

greetings

**Comment by therealpxc** [comment] 2017-10-31 03:27
I thought I filed an issue (was I out of line? did it get deleted?) but I can't seem to see it.

Anyway, after fumbling through some trouble with Perl module dependencies along the way, I successfully installed a few KDE apps on my Macbook, including Konsole.

None of the defaults are in place, and it doesn't read the Linux config directories which are already in my home directory, so I noticed some very strange behavior due to lack of configuration. But once I figured out where they needed to go and put them in place, Konsole itself seems to mostly work! The only major issue I still have is that the control key appears not to work.

Here's a screenshot of Konsole in action on this Macbook Pro:
<img width="1680" alt="screen shot 2017-10-30 at 8 18 47 pm" src="https://user-images.githubusercontent.com/3180910/32206074-499f1ed8-bdb0-11e7-9a4e-6aef337c20ec.png">

As a longtime KDE user, I have (to my surprise!) missed Konsole dearly on macOS in the months since I've been required to use it on my work computer. Thank you so much for working on this! What can I do in the way of further testing or documentation on this to help?

**Comment by yurikoles** [comment] 2017-10-31 19:36
@sl1pkn07 could you create a PR for this?

**Comment by sl1pkn07** [comment] 2017-10-31 19:43
where? master or my branch? 

git branch in my local (after purge and redownload) only see master, but in githubs i can see 7 branches

**Comment by yurikoles** [comment] 2017-10-31 19:51
@sl1pkn07 I also see no branches in my clone except the master one.

**Comment by sl1pkn07** [comment] 2017-10-31 19:54
NP. but my last issue with github (few days ago) they took one day and lots of emails xd

**Comment by sl1pkn07** [comment] 2017-10-31 19:57
done.

**Comment by franklinyu** [comment] 2017-11-01 04:48
@therealpxc I don't think it's even possible to delete a pull request or issue. Even project owners can only close it, or modify the title and content.

**Comment by sl1pkn07** [comment] 2017-11-02 10:31
```git clone will only download the master branch by default.

After cloning, running git fetch --all should download the other branches as well.

Cheers```

MOG ><

**Comment by therealpxc** [comment] 2017-11-02 20:15
> @therealpxc I don't think it's even possible to delete a pull request or issue. Even project owners can only close it, or modify the title and content.

I thought so! I must have just forgotten to submit the issue without realizing it.

Should I file issues about the missing defaults here or on the upstream KDE bug tracker?

**Comment by sl1pkn07** [comment] 2017-11-02 20:32
try softlink /usr/local/share/konsole to ~/Libraryes/"Application Support"

ot the content of /usr/local/share/konsole/* to ~/Libraryes/"Application Support"/konsole

**Comment by therealpxc** [comment] 2017-11-02 20:39
I got all the symlinks that I needed in place, but the app should ship with defaults it can find like on Linux and the free Unices, that's all.

Have you gotten the control key to work right?

**Comment by franklinyu** [comment] 2017-11-02 21:08
I'm not sure which one is preferred. Shall Konsole look at `/usr/local/share/konsole`? Or shall package managers (like Homebrew) automatically link to it from `~/Library/Application Support` on Mac?

**Comment by sl1pkn07** [comment] 2017-11-02 21:08
i'm not mean if you have a missing link, probably ok, but, in my test, the files stored in /usr/local/share/konsole:

```
└───╼  yaourt -Ql konsole |grep share/konsole
konsole /usr/share/konsole/
konsole /usr/share/konsole/BlackOnLightYellow.colorscheme
konsole /usr/share/konsole/BlackOnRandomLight.colorscheme
konsole /usr/share/konsole/BlackOnWhite.colorscheme
konsole /usr/share/konsole/BlueOnBlack.colorscheme
konsole /usr/share/konsole/Breeze.colorscheme
konsole /usr/share/konsole/DarkPastels.colorscheme
konsole /usr/share/konsole/GreenOnBlack.colorscheme
konsole /usr/share/konsole/Linux.colorscheme
konsole /usr/share/konsole/RedOnBlack.colorscheme
konsole /usr/share/konsole/Solarized.colorscheme
konsole /usr/share/konsole/SolarizedLight.colorscheme
konsole /usr/share/konsole/WhiteOnBlack.colorscheme
konsole /usr/share/konsole/default.keytab
konsole /usr/share/konsole/linux.keytab
konsole /usr/share/konsole/solaris.keytab
```
NOTE: this list of files is taked from my linux installation, the path is different

should be linked in ~/Libraryes/"Application Support"/konsole

i'cant test the program now, because i'm testing all kf5 installation and don't have the konsole installed

**Comment by franklinyu** [comment] 2017-11-02 21:09
Yeah I can tell you are running Arch from `yaourt` LOL

**Comment by sl1pkn07** [comment] 2017-11-02 21:10
yep. is my main rig and my patches/fix is based in my linux installation, and ported to my hackintoch rig for test

**Comment by franklinyu** [comment] 2017-11-02 21:11
Nevertheless, does KDE team want it in `/usr/share`, `/usr/local/share` or `Application Support, on Mac? I think their opinion affects how we should deal with this issue.

**Comment by sl1pkn07** [comment] 2017-11-02 21:14
brew prohibited store files in Applications or libray folder (see #133), need do this by hand

or 'm not sure if can do it with brew `post_install` function

**Comment by franklinyu** [comment] 2017-11-02 21:18
Yes, I meant the same. If it should be `/usr/local/share` then we modify the install hook; if it should be in `Application Support` then we modify the caveats.

Or even consider something like [Homebrew Cask](https://caskroom.github.io/).

**Comment by sl1pkn07** [comment] 2017-11-02 21:22
the path can be changed by cmake option, but the problem is brew iself

and yes. that is applied on my repo (in test in this moment)

https://github.com/sl1pkn07/homebrew-kde/tree/sl1pkn07

**Comment by therealpxc** [comment] 2017-11-02 21:28
Would it be so bad to just use the Linux conventions on where configs go? Or to have it fall back to the Linux directories? It would simplify dotfile syncing a little.

**Comment by franklinyu** [comment] 2017-11-03 02:17
@sl1pkn07 So you mean Homebrew tells CMake that configuration file should be at `Application Support`? That's very weird given the sandbox policy.

**Comment by sl1pkn07** [comment] 2017-11-03 10:31
No, i mean the path can be change in cmake (in normal use), but brew refuse install due sandbox

**Comment by franklinyu** [comment] 2017-11-03 15:37
Then how about configure CMake to just install the share files in `/share` folder within keg? Like `/usr/local/Cellar/konsole/17.08.0/share`?

**Comment by sl1pkn07** [comment] 2017-11-03 16:18
by defaul brew install the files in /usr/local/Cellar/foo (seems is the sandbox), then symlink the files in two paths, /usr/local/opt/foo and /usr/local when install the formulas

i'm not sure why this behavior (i think link twice is a useless, i prefer get rid /usr/local/opt and keep /usr/local 

but i'm sure you can change the path, but only into the sadbox, and then lead to brew the rest when make the symlinks

for example, you want install the libraries into (final path, after brew do the symlinks) /usr/local/brawbraw instead of /usr/local/lib. If you use the cmake option -CMAKE_INSTALL_LIBDIR=brawbraw.  then brew, when build the project and install the files into /usr/local/Cellar/foo/brawbraw (into the sandbox), and then brew directly create symlinks to /usr/local/brawbraw (and /usr/local/opt/foo/brawbraw)

in this case, brew avoid install any file into ~/Library/"Application Support" (this directory is used like /usr/local/share (same effect), but only for GUI programs , then is need create by hand a symlink from /usr/local/share/>program share< to ~/Library/"Application Support"

in case of konsole:

      ln -sf "$(brew --prefix)/share/konsole" ~/Library/"Application Support"

and if you want view the icons in the gui:

     ln -sf "$(brew --prefix)/share/icons/breeze/breeze-icons.rcc" ~/Library/"Application Support"/konsole/icontheme.rcc

the therealpxc problem seems the mac keyboard layout is not exist (the keytab) (maybe bug, or maybe not exist at the moment), then can be not used 

anyway i need make some test and fix possibles issues when build the frameworks, then do fixes in the applications and finaly merge the changes in this repo

greetings

**Closed** 2019-03-17 14:58 UTC
