### ISSUE TITLE
Installing Okular

### ISSUE THREAD

**Issue by surrutiaquir** [KDE-mac/homebrew-kde#292] opened 2019-04-14 04:02 UTC
Hi,
I'm trying to install Okular by `brew install kde-mac/kde/okular` but I get the following error:

```
/usr/local/opt/qt/include/QtCore/qresultstore.h:162:38: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
            return addResults(index, 0, 0, totalCount);
                                     ^
                                     nullptr
In file included from src/notifications_interface.cpp:12:
In file included from src/notifications_interface.h:21:
In file included from /usr/local/opt/qt/include/QtDBus/QtDBus:3:
In file included from /usr/local/opt/qt/include/QtDBus/QtDBusDepends:3:
In file included from /usr/local/opt/qt/include/QtCore/QtCore:237:
/usr/local/opt/qt/lib/QtCore.framework/Headers/qthreadstorage.h:72:23: warning: zero as null pointer constant [-Wzero-as-null-pointer-constant]
    if (!v) v = d.set(0);
                      ^
                      nullptr
2 warnings generated.
ninja: build stopped: subcommand failed.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/KDE-mac/homebrew-kde/issues

These open issues may also help:
kf5-knotifications: error: no type named 'setBadgeLabelText' in namespace 'QtMac' https://github.com/KDE-mac/homebrew-kde/issues/291

```

Any suggestion? Thank you in advance!

**Comment by yurikoles** [comment] 2019-04-14 08:02
Thanks for reporting, but it's seems to be duplicate of #291

**Closed by yurikoles** 2019-04-14 08:02 UTC

**Comment by yurikoles** [comment] 2019-04-14 08:04
@surrutiaquir is this error during build of `kf5-knotifications`?

**Comment by surrutiaquir** [comment] 2019-04-14 19:07
@yurikoles Yes, it is!

**Comment by surrutiaquir** [comment] 2019-04-21 03:42
Hi again,
The error involving `kf5-knotifications` was fixed, and now I was able to finish the installation getting the following message:

```
You need to take some manual steps in order to make this formula work:
  ln -sfv "$(brew --prefix)/share/okular" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/kconf_update" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/config.kcfg" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/kservices5" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/kservicetypes5" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/kxmlgui5" "$HOME/Library/Application Support"
  ln -sfv "$(brew --prefix)/share/metainfo" "$HOME/Library/Application Support"
  mkdir -pv "$HOME/Applications/KDE"
  ln -sfv "$(brew --prefix)/opt/okular/bin/okular.app" "$HOME/Applications/KDE/"
```

I did it, but I'm still unable to run Okular. In the terminal appears the message:
`dbus[6402]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!`

and the GUI shows this message:
> Unable to find the Okular component: The shared library was not found.

Any idea about what is wrong ? Thanks in advance...

**Comment by yurikoles** [comment] 2019-04-21 09:40
```
$ brew info dbus 
dbus: stable 1.12.12 (bottled), HEAD
Message bus system, providing inter-application communication
https://wiki.freedesktop.org/www/Software/dbus
/usr/local/Cellar/dbus/1.12.12 (76 files, 2MB) *
  Poured from bottle on 2018-12-10 at 11:29:57
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/dbus.rb
==> Dependencies
Build: xmlto ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
To have launchd start dbus now and restart at login:
  brew services start dbus
```

**Comment by yurikoles** [comment] 2019-04-21 10:57
@surrutiaquir please re-apply `"$(brew --repo kde-mac/kde)/tools/install.sh"`
